### ISSUE TITLE
JsPlumb connector lines flicker on block update

### ISSUE THREAD

**Issue by maxknivets** [progrium/vizgo#27]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34922382/82642552-c8c83900-9c16-11ea-9df8-4efa93ecb199.gif)

**Comment by progrium** [comment]
I believe this is due to how I make the connections. Since we redraw everything that needs to be updated like most component systems and we tie the connections to their components, we can't connect to blocks that haven't been made yet. So I add a short delay to the call to draw the connection. To fix this we'd need to figure out a different approach because reducing the delay will risk it not succeeding.

**Comment by progrium** [comment]
Another approach that's maybe more of a workaround is only redrawing jsplumb when we need to, but if the dom elements they're associated with change, I'm not sure how it will react (could break it like in previous versions, not updating classes etc)

**Comment by progrium** [comment]
This is probably less noticeable on faster machines, and I've tuned it a little since. But the ideal thing would be to drop jsPlumb. The only reason I haven't is because of their line drawing code. Maybe you can go try to find it and try making some prototypes replicating just the line drawing based on the jsPlumb code.

**Comment by progrium** [comment]
No more jsplumb for lines! New approach does not flash. See a710944e28aa4fada38eab23e1869596c7a23af6
